### ISSUE TITLE
【漏洞】定时动态发送失败

### ISSUE THREAD

**Issue by WangJiarun** [MoyuScript/bilibili-api#200]
**Python 版本：** 3.9

**模块版本：** 6.1.2

**运行环境：** Windows 

**模块路径：** bilibili_api.dynamic

**报错信息：**

调用过程误报错

**报错代码：**

```python
# 调用过程误报错
```

---

发送带有@人的定时动态，到达发送时间后前往t.bilibili.com会发现发送失败，提示”定时发布失败,系统错误:500104”

**Comment by Passkou** [comment]
请补充相关代码和报错信息
