### ISSUE TITLE
【提问】视频上传接口对多P好像有限制

### ISSUE THREAD

**Issue by zzc10086** [MoyuScript/bilibili-api#204]
**Python 版本：** 无

**模块版本：** 无
**运行环境：**  Linux

---

`https://member.bilibili.com/x/vu/web/add`这个接口应该添加了多p上传限制。今天用CURL手动提交共2p的稿件时报分p达到上限的错误

**Comment by Passkou** [comment]
网页端从去年一月开始就说因为有bug在维护，只能传单P，直到现在都还没搞好，目前只能通过客户端传，改天我看看能不能搞到客户端的上传接口（成功概率比较小，因为客户端可能没法调试

**Comment by zzc10086** [comment]
我用fiddler抓到了投稿客户端的api,不过要客户端的access_key,用cookie显示未登陆  
`https://member.bilibili.com/x/vu/client/add?access_key=*************`  
其他的(http投,携带的json)用web端的就可以了

**Comment by MoyuScript** [comment]
是这样，这个问题无法解决，因为我看不到客户端的代码，不知道他的签名方式，虽然网络包看的到
