### ISSUE TITLE
关于用pyinstaller等打包软件打包后出现问题

### ISSUE THREAD

**Issue by 382009** [MoyuScript/bilibili-api#206]
正常运行python xxx.py可以正常使用
使用pyinstaller导出后出现
![image](https://user-images.githubusercontent.com/13533545/127487808-0a7f8fe7-2a50-4a57-b756-cc9fb594983c.png)
'NoneType' object is not subscriptable
本人没有能力解决，寻求解决

**Comment by MoyuScript** [comment]
请使用 issue 模板
