### ISSUE TITLE
【提问】使用sync函数产生错误

### ISSUE THREAD

**Issue by licoded** [MoyuScript/bilibili-api#207]
**Python 版本：** 3.8.2

**模块版本：** 6.1.2

**运行环境：** MacOS

---

按照 [文档：同步执行异步代码](https://www.moyu.moe/bilibili-api/#/sync-executor) 编写了如下代码

```python
from bilibili_api import sync
from bilibili_api.favorite_list import get_video_favorite_list, get_video_favorite_list_content

favorite_list = sync(get_video_favorite_list(uid=uid, credential=credential))
    list = favorite_list['list']
    for i in range(len(list)):
        favorite = list[i]
        favorite['list'] = sync(get_video_favorite_list_content(media_id=favorite['id']))
```

产生报错 RuntimeError: There is no current event loop in thread 'Thread-14'.

之前没用过Python的异步模块，搜索了一上午后没有解决，所以请求您的帮助:pray:

**Comment by licoded** [comment]
经检查当在Flask换将中使用上述代码才会报错，单独使用这段代码是没有问题的。

**Comment by MoyuScript** [comment]
Flask 好像对每个请求都会开一个线程，非主线程会导致 event_loop 不存在，因此加入以下代码即可解决问题：

```python
@app.before_request
def before_request():
    asyncio.set_event_loop(asyncio.new_event_loop())

# 其他代码略
```

**Comment by licoded** [comment]
> Flask 好像对每个请求都会开一个线程，非主线程会导致 event_loop 不存在，因此加入以下代码即可解决问题：
> 
> ```python
> import asyncio
> 
> @app.before_request
> def before_request():
>     asyncio.set_event_loop(asyncio.new_event_loop())
> 
> # 其他代码略
> ```
> 
> 或者也可以参考这个：https://flask.palletsprojects.com/en/2.0.x/async-await/?highlight=async
> 
> Flask 使用 async 特性

非常感谢
