### ISSUE TITLE
【提问】关于用pyinstaller等打包软件打包后出现问题

### ISSUE THREAD

**Issue by 382009** [MoyuScript/bilibili-api#210]
**Python 版本：** 3.9.6

**模块版本：** x.x.x

**运行环境：** Windows

---
正常运行python xxx.py可以正常使用
使用pyinstaller导出后出现
![image](https://user-images.githubusercontent.com/13533545/128594270-bcbc8eed-3d9b-47e9-af90-55b9ffff0e22.png)

'NoneType' object is not subscriptable
本人没有能力解决，寻求解决

**Comment by MoyuScript** [comment]
请提供完整代码

**Comment by 382009** [comment]
![image](https://user-images.githubusercontent.com/13533545/128595199-9373b0f3-05fb-46c7-b38b-16387da707c7.png)
我是直接从开发文档上copy下来的代码 用pyinstaller打包后 仍然会出现以上问题

**Comment by MoyuScript** [comment]
猜测是你打包配置错误，你要把 `data` 文件夹一起打包了，这个打包器我没怎么用过，所以不是很清楚。

这个 `data` 文件夹下是包含了所有 API 的接口 JSON 文件，目前猜测是打包的时候没包含进去，导致获取接口时结果为 None

**Comment by 382009** [comment]
您好 我用该打包器的-add-data参数 将data打包进了exe了，但是仍然出现了这个问题
请问您用的是什么打包器呢 如果方便打包成exe的话

**Comment by 382009** [comment]
谢谢您 我修改了部分参数 可以正常运行了 感谢作者耐心回答

**Comment by laosong-2020** [comment]
> 谢谢您 我修改了部分参数 可以正常运行了 感谢作者耐心回答

我也遇到了同样的问题，能麻烦告诉我一下最后的参数是什么样嘛？或者spec文件怎么写的？感谢
