### ISSUE TITLE
【漏洞】{接口返回错误代码：21150，信息：投稿入口升级中，请重新编辑稿件。}

### ISSUE THREAD

**Issue by googidaddy** [MoyuScript/bilibili-api#211]
接口返回错误代码：21150，信息：投稿入口升级中，请重新编辑稿件。
接口需要更新了？

**Comment by googidaddy** [comment]
最近投稿接口好像出问题了。能看看是啥原因么？

**Comment by MoyuScript** [comment]
接口应该是变了，这个接口之后要大改一次，因为网页端不支持上传多 P 视频

**Comment by googidaddy** [comment]
> 接口应该是变了，这个接口之后要大改一次，因为网页端不支持上传多 P 视频
了解.

**Comment by MoyuScript** [comment]
7.0.0：https://www.moyu.moe/bilibili-api/#/examples/video_uploader

**Comment by googidaddy** [comment]
太好了
