### ISSUE TITLE
【需求】{搜索功能}

### ISSUE THREAD

**Issue by tower-town** [MoyuScript/bilibili-api#212]
搜索视频的功能，可以像everything那样搜索视频或者locate命令（Linux）一样。

流程：
1、扫描全部视频信息（包括标题、标签、up主、分p标题）记录保存到搜索文件中。
2、之后搜索文件定时保存增量视频信息。
3、用户只需搜索“搜索文件”的内容然后验证文件的存在，不存在会被标记到搜索文件中。
4、再次搜索仍能搜索到，只是有标记，但可以有一个选项忽略被标记内容。

**Comment by MoyuScript** [comment]
这个库只提供基本的API调用，复杂的自己另外实现
