### ISSUE TITLE
【建议】{Solve： annot connect to host api.bilibili.com:443 ssl:True}

### ISSUE THREAD

**Issue by uiuing** [MoyuScript/bilibili-api#213]
**I encountered a problem while using:**
"Iohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.bilibili.com:443 ssl:True"

**The following is my solution：**

1. Go to the file: bilibili_api.utils.network

2. Add: "from aiohttp import TCPConnector"

3. Go to line 173
"__session = aiohttp.ClientSession(loop=asyncio.get_event_loop())"
change into:
"__session = aiohttp.ClientSession(connector=TCPConnector(verify_ssl=False),loop=asyncio.get_event_loop())"

**Comment by MoyuScript** [comment]
This module is using HTTPS by default, not support HTTP currently
