### ISSUE TITLE
【提问】参数问题

### ISSUE THREAD

**Issue by compiledSuccessfully** [MoyuScript/bilibili-api#215]
**Python 版本：** 3.9

**模块版本: bilibili-api-6.1.3

**运行环境：** Windows /pycharm

---
![screenshot_08-17_21 05](https://user-images.githubusercontent.com/29682883/129730811-bb61c605-3daa-406f-8334-560df7d98fd7.jpg)

**Comment by MoyuScript** [comment]
这个不影响使用，之后会修改一下
