### ISSUE TITLE
【提问】国外VPS上传总是失败(大文件)

### ISSUE THREAD

**Issue by compiledSuccessfully** [MoyuScript/bilibili-api#216]
b站上传目前有两种模式，分别为bup和bupfetch模式。

bup：国内常用模式，视频直接上传到b站投稿系统。
bupfetch：目前见于国外网络环境，视频首先上传至第三方文件系统，上传结束后通知bilibili投稿系统，再由b站投稿系统从第三方系统拉取视频，以保证某些地区用户的上传体验。

这个如何选择?

**Comment by MoyuScript** [comment]
默认是用国内的上传方式，我对国外用户上传的不是很了解
