### ISSUE TITLE
【需求】{小声问一句能添加一个上传字幕的接口吗？}

### ISSUE THREAD

**Issue by googidaddy** [MoyuScript/bilibili-api#218]
希望能加上上传视频字幕的接口
另外好像API文档打不开了

**Comment by MoyuScript** [comment]
之后看看，服务器被 DDoS 了

**Comment by valkjsaaa** [comment]
subtitle 我在之前某个版本的 fork 里实现过，可以参考： https://github.com/valkjsaaa/bilibili_api/blob/731f8a3aa3f61ff981ffb741ded4f34f43f96cf0/bilibili_api/video.py#L939

**Comment by MoyuScript** [comment]
尝试 v8.1.0

`pip install --upgrade bilibili-api==8.1.0`
