### ISSUE TITLE
API 变更

### ISSUE THREAD

**Issue by valkjsaaa** [MoyuScript/bilibili-api#220]
[这个 URL](https://github.com/MoyuScript/bilibili-api/blob/07f638807387b459a20854890d7c20de6aadc1fd/bilibili_api/data/api/interactive_video.json#L4) 好像 404 了

 目前认为新的 URL 应该是这个：https://member.bilibili.com/x/vupre/web/archive/view

**Comment by phigrey** [comment]
@valkjsaaa 你说的没错，是变更了。 @MoyuScript 已更新了。

**Comment by phigrey** [comment]
@MoyuScript 有空出个包吧

**Comment by MoyuScript** [comment]
试试 v8.0.0
