### ISSUE TITLE
【提问】 LiveDanmaku中的Live监听在开播时会激活两次

### ISSUE THREAD

**Issue by Hato626** [MoyuScript/bilibili-api#229]
**Python 版本：** 3.9.6

**模块版本：** 8.0.0

**运行环境：** Windows

---

如题所示, LiveDanmaku中的Live监听在开播时会激活两次
![image](https://user-images.githubusercontent.com/63497854/133931680-e78da98a-510d-468a-b1d7-020b2897c501.png)
![image](https://user-images.githubusercontent.com/63497854/133931718-36944121-eafe-4cbb-857e-5918ed06defd.png)
![image](https://user-images.githubusercontent.com/63497854/133931785-c8ef57c1-4c8d-48e8-be85-61cf5b9afac7.png)

这是属于bug还是特性呢

**Comment by MoyuScript** [comment]
只是原封不动转发原事件而已，你可以自己写个防抖函数

**Comment by Hato626** [comment]
懂了，谢谢

**Comment by Hato626** [comment]
B站这么做太反直觉了

**Comment by MoyuScript** [comment]
突然想了一下python怎么写防抖节流函数（一般都是前端开发才有这个概念的）

你可以参考一下我刚刚写的：https://gist.github.com/MoyuScript/5114fa0f22a32972e5e65b37d97538fa

还蛮有意思的
