### ISSUE TITLE
【异常】{aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected}

### ISSUE THREAD

**Issue by xzh12** [MoyuScript/bilibili-api#231]
**Python 版本：** 3.9

**模块版本：** 8.1.0

**运行环境：** mac

---
等的时间超过5s。就报错
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

**Comment by MoyuScript** [comment]
自行用 `try...except` 包裹，不构成问题
