### ISSUE TITLE
【漏洞】VideoUploader 获取上传结果时没有处理 code > 0 的情况

### ISSUE THREAD

**Issue by wshrzzz** [MoyuScript/bilibili-api#232]
**Python 版本：** 3.8.10

**模块版本：** 7.0.1

**运行环境：** wsl2 Ubuntu20.0

**模块路径：** bilibili_api.video_uploader

**报错信息：**

```
File "/mnt/c/scripts/upload/upload_process.py", line 192, in upload_video
    result = await uploader.start()
  File "/mnt/c/wsl_env/lib/python3.8/site-packages/bilibili_api/video_uploader.py", line 454, in start
    raise e
  File "/mnt/c/wsl_env/lib/python3.8/site-packages/bilibili_api/video_uploader.py", line 447, in start
    result = await task
  File "/mnt/c/wsl_env/lib/python3.8/site-packages/bilibili_api/video_uploader.py", line 430, in _main
    result = await self._submit(videos, cover_url)
  File "/mnt/c/wsl_env/lib/python3.8/site-packages/bilibili_api/video_uploader.py", line 695, in _submit
    self.dispatch(VideoUploaderEvents.AFTER_SUBMIT.value, data['data'])
KeyError: 'data'
```

**报错代码：**

```python
data = await resp.json()

if data['code'] < 0:
    err = ResponseCodeException(data['code'], data['message'])
    self.dispatch(VideoUploaderEvents.SUBMIT_FAILED.value, {"err": err})
    raise err

self.dispatch(VideoUploaderEvents.AFTER_SUBMIT.value, data['data'])
return data['data']
```

---

{'code': 21001, 'message': '参数错误', 'ttl': 1}
{'code': 21005, 'message': 'Tag不能为空，总数量不能超过12个， 并且单个不能超过20个 字', 'ttl': 1}
偶然看到的两个错误的返回例子，上传失败后消息没有被正确处理，于是抛出上述错误

**Comment by MoyuScript** [comment]
理论上这不是我的问题，这种情况 `code` 应该为负数，是 b 站的问题。

根据大量数据观察表明，请求正常为 0，错误为负数，警告为正数。

也只能将错就错了

**Comment by wshrzzz** [comment]
> 理论上这不是我的问题，这种情况 `code` 应该为负数，是 b 站的问题。
> 
> 根据大量数据观察表明，请求正常为 0，错误为负数，警告为正数。
> 
> 也只能将错就错了

但结果是这两种code的情况下，投稿行为自身并没有成功
而且即便正值是警告，在没有data的时候，这个地方也会直接抛出KeyError，外面调用的地方不就拿不到返回的警告了吗

**Comment by MoyuScript** [comment]
将错就错指的是把正值也视为错误

**Comment by wshrzzz** [comment]
> 将错就错指的是把正值也视为错误

哦，好吧
![10C184A3](https://user-images.githubusercontent.com/5547526/134905551-8da97590-d8ea-40aa-8982-0c54f593cc3d.png)

**Comment by MoyuScript** [comment]
33d943feab74df242f5e3aa11723078bf66cca1b 解决

**Comment by MoyuScript** [comment]
8.2.0 已发布，已解决该问题
