### ISSUE TITLE
【需求】channel 信息需要更新

### ISSUE THREAD

**Issue by WeishuangLiang** [MoyuScript/bilibili-api#235]
b站的分区修改过，channel.json里面的部分tid已经不对了。

**Comment by MoyuScript** [comment]
他写死在 js 里头的，目前还没找到一键获取最新分区信息的接口，只能手动更新下了

**Comment by WeishuangLiang** [comment]
那只能手动改了啊

**Comment by MoyuScript** [comment]
4567bdf86e0a12010fb6f9035335dc28e17c71b3 解决

**Comment by MoyuScript** [comment]
8.2.0 已发布，已解决该问题
