### ISSUE TITLE
【提问】v8 没有 web_search 了吗

### ISSUE THREAD

**Issue by Louisover** [MoyuScript/bilibili-api#236]
**Python 版本：** 3.9.7

**模块版本：** 8.2.0

**运行环境：** Linux

---

请问，v8版本删除了web_search吗，看见common.json有，但没看见common.py

**Comment by MoyuScript** [comment]
貌似被哪个 commit 不小心删掉了，下次加回来

**Comment by MoyuScript** [comment]
v8.3.0 解决，在模块 `bilibili_api.misc` 里面，文档稍后补上
