### ISSUE TITLE
【漏洞】video_uploader.py 使用账号密码登录获取 access_key 失败

### ISSUE THREAD

**Issue by 122313** [MoyuScript/bilibili-api#243]
**Python 版本：** 3.9

**模块版本：** 8.3.1

**运行环境：** MacOS

**模块路径：** bilibili_api.video_uploader

**报错信息：**

```
调用login接口，接口返回
{'code':86066,'message':'该账号冻结中','ttl':1,'data':None}
```

**报错代码：**

```python
r = await resp.json()
        if r["code"] < 0:
            raise ApiException(r["message"])

        return r["data"] # r = {'code':86066,'message':'该账号冻结中','ttl':1,'data':None}
```

---

接口返回信息错误，可能是接口变更，导致登录不可用

我切换了两个账号，都是一样的报错，可重复复现

账号是正常可登录的，也不存在冻结

需要排查一下接口参数是否更新

**Comment by CatOverrun** [comment]
> 完了，这个接口废了

开发者还会考虑继续做视频投稿方面的功能么？

**Comment by MoyuScript** [comment]
> > 完了，这个接口废了
> 
> 开发者还会考虑继续做视频投稿方面的功能么？

Web 端的投稿接口倒是可以，问题是 Web 端不能投多 P 视频，目前好像只有 PC 投稿工具支持。如果实在不行，我就做会 Web 端的算了

**Comment by MoyuScript** [comment]
v9.0.0 已切换到 Web 端接口，无法上传多 p 视频了。另外就是接口参数有变化要注意一下，其他大体都没变

**Comment by WeishuangLiang** [comment]
v9.0上传视频出错
（不懂具体的代码，照着其他的代码改的，出现了报错信息）

```from bilibili_api import sync, video_uploader,Credential

async def main():

    SESSDATA = ''
    BUVID3 = ''
    BILI_JCT = ''

    credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3)
    for i in range (1,2):

    # 具体请查阅相关文档
        meta = {
                "act_reserve_create": 0,
                "copyright": 1,
                "source": "",
                "desc": "",
                "desc_format_id": 0,
                "dynamic": "",
                "interactive": 0,
                "open_elec": 1,
                "no_reprint": 1,
                "subtitles": {
                    "lan": "",
                    "open": 0
                },
                "tag": "shishitag",
                "tid": 172,
                "title": "shishititle",
                "up_close_danmaku": False,
                "up_close_reply": False,
                "up_selection_reply": False
            }
        # page = video_uploader.VideoUploaderPage(video_stream=open('E:\\Files\\python\\Blikes\\Video\\{}.mp4'.format(1), 'rb'), title="王者激励伍", description='', extension='mp4')
        # uploader = video_uploader.VideoUploader([page], meta, credential, threads=5,cover_stream=open('Cover.png', 'rb'),cover_type='image/png')
        page = video_uploader.VideoUploaderPage(path = 'E:\\Files\\python\\result.mp4', title = 'shishi' , description='')
        uploader = video_uploader.VideoUploader([page], meta, credential, 'E:\\Files\\python\\Cover.jpg')
        @uploader.on("__ALL__")
        async def ev(data):
            print(data)

        await uploader.start()


sync(main())```

 运行这段代码会出现如下报错信息：
 File "e:/Files/python/Blikes/uploader.py", line 45, in <module>
    sync(main())
  File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\utils\sync.py", line 16, in sync
    return loop.run_until_complete(coroutine)
  File "D:\ProgramData\Anaconda3\envs\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "e:/Files/python/Blikes/uploader.py", line 42, in main
    await uploader.start()
  File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 411, in start
    raise e
  File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 404, in start
    result = await task
  File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 374, in _main
    data = await self._upload_page(page)
  File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 448, in _upload_page
    preupload = await self._preupload(page)
  File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 223, in _preupload
    url = self._get_upload_url(preupload)
  File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 489, in _get_upload_url
    return "https:" + preupload["endpoint"] + "/" + preupload["upos_uri"].removeprefix("upos://")
AttributeError: 'str' object has no attribute 'removeprefix'

**Comment by MoyuScript** [comment]
> v9.0上传视频出错 （不懂具体的代码，照着其他的代码改的，出现了报错信息）
> 
> ```
> 
> async def main():
> 
>     SESSDATA = ''
>     BUVID3 = ''
>     BILI_JCT = ''
> 
>     credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3)
>     for i in range (1,2):
> 
>     # 具体请查阅相关文档
>         meta = {
>                 "act_reserve_create": 0,
>                 "copyright": 1,
>                 "source": "",
>                 "desc": "",
>                 "desc_format_id": 0,
>                 "dynamic": "",
>                 "interactive": 0,
>                 "open_elec": 1,
>                 "no_reprint": 1,
>                 "subtitles": {
>                     "lan": "",
>                     "open": 0
>                 },
>                 "tag": "shishitag",
>                 "tid": 172,
>                 "title": "shishititle",
>                 "up_close_danmaku": False,
>                 "up_close_reply": False,
>                 "up_selection_reply": False
>             }
>         # page = video_uploader.VideoUploaderPage(video_stream=open('E:\\Files\\python\\Blikes\\Video\\{}.mp4'.format(1), 'rb'), title="王者激励伍", description='', extension='mp4')
>         # uploader = video_uploader.VideoUploader([page], meta, credential, threads=5,cover_stream=open('Cover.png', 'rb'),cover_type='image/png')
>         page = video_uploader.VideoUploaderPage(path = 'E:\\Files\\python\\result.mp4', title = 'shishi' , description='')
>         uploader = video_uploader.VideoUploader([page], meta, credential, 'E:\\Files\\python\\Cover.jpg')
>         @uploader.on("__ALL__")
>         async def ev(data):
>             print(data)
> 
>         await uploader.start()
> 
> 
> sync(main())```
> 
>  运行这段代码会出现如下报错信息：
>  File "e:/Files/python/Blikes/uploader.py", line 45, in <module>
>     sync(main())
>   File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\utils\sync.py", line 16, in sync
>     return loop.run_until_complete(coroutine)
>   File "D:\ProgramData\Anaconda3\envs\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
>     return future.result()
>   File "e:/Files/python/Blikes/uploader.py", line 42, in main
>     await uploader.start()
>   File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 411, in start
>     raise e
>   File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 404, in start
>     result = await task
>   File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 374, in _main
>     data = await self._upload_page(page)
>   File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 448, in _upload_page
>     preupload = await self._preupload(page)
>   File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 223, in _preupload
>     url = self._get_upload_url(preupload)
>   File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 489, in _get_upload_url
>     return "https:" + preupload["endpoint"] + "/" + preupload["upos_uri"].removeprefix("upos://")
> AttributeError: 'str' object has no attribute 'removeprefix' 
> ```

升级 python 版本到 3.9

**Comment by WeishuangLiang** [comment]
> > v9.0上传视频出错 （不懂具体的代码，照着其他的代码改的，出现了报错信息）
> > ```
> > 
> > async def main():
> > 
> >     SESSDATA = ''
> >     BUVID3 = ''
> >     BILI_JCT = ''
> > 
> >     credential = Credential(sessdata=SESSDATA, bili_jct=BILI_JCT, buvid3=BUVID3)
> >     for i in range (1,2):
> > 
> >     # 具体请查阅相关文档
> >         meta = {
> >                 "act_reserve_create": 0,
> >                 "copyright": 1,
> >                 "source": "",
> >                 "desc": "",
> >                 "desc_format_id": 0,
> >                 "dynamic": "",
> >                 "interactive": 0,
> >                 "open_elec": 1,
> >                 "no_reprint": 1,
> >                 "subtitles": {
> >                     "lan": "",
> >                     "open": 0
> >                 },
> >                 "tag": "shishitag",
> >                 "tid": 172,
> >                 "title": "shishititle",
> >                 "up_close_danmaku": False,
> >                 "up_close_reply": False,
> >                 "up_selection_reply": False
> >             }
> >         # page = video_uploader.VideoUploaderPage(video_stream=open('E:\\Files\\python\\Blikes\\Video\\{}.mp4'.format(1), 'rb'), title="王者激励伍", description='', extension='mp4')
> >         # uploader = video_uploader.VideoUploader([page], meta, credential, threads=5,cover_stream=open('Cover.png', 'rb'),cover_type='image/png')
> >         page = video_uploader.VideoUploaderPage(path = 'E:\\Files\\python\\result.mp4', title = 'shishi' , description='')
> >         uploader = video_uploader.VideoUploader([page], meta, credential, 'E:\\Files\\python\\Cover.jpg')
> >         @uploader.on("__ALL__")
> >         async def ev(data):
> >             print(data)
> > 
> >         await uploader.start()
> > 
> > 
> > sync(main())```
> > 
> >  运行这段代码会出现如下报错信息：
> >  File "e:/Files/python/Blikes/uploader.py", line 45, in <module>
> >     sync(main())
> >   File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\utils\sync.py", line 16, in sync
> >     return loop.run_until_complete(coroutine)
> >   File "D:\ProgramData\Anaconda3\envs\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
> >     return future.result()
> >   File "e:/Files/python/Blikes/uploader.py", line 42, in main
> >     await uploader.start()
> >   File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 411, in start
> >     raise e
> >   File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 404, in start
> >     result = await task
> >   File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 374, in _main
> >     data = await self._upload_page(page)
> >   File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 448, in _upload_page
> >     preupload = await self._preupload(page)
> >   File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 223, in _preupload
> >     url = self._get_upload_url(preupload)
> >   File "D:\ProgramData\Anaconda3\envs\python38\lib\site-packages\bilibili_api\video_uploader.py", line 489, in _get_upload_url
> >     return "https:" + preupload["endpoint"] + "/" + preupload["upos_uri"].removeprefix("upos://")
> > AttributeError: 'str' object has no attribute 'removeprefix' 
> > ```
> 
> 升级 python 版本到 3.9

问题解决，感谢：-）

**Comment by xzh12** [comment]
通过模拟 web 提交。。要么频率太高，要么转码失败。。关键，好几个小时了，还是审核状态啊。。没办法玩啊，555

**Comment by MoyuScript** [comment]
> 通过模拟 web 提交。。要么频率太高，要么转码失败。。关键，好几个小时了，还是审核状态啊。。没办法玩啊，555

漏写了一行导致的，现在在修了

**Comment by MoyuScript** [comment]
> > 通过模拟 web 提交。。要么频率太高，要么转码失败。。关键，好几个小时了，还是审核状态啊。。没办法玩啊，555
> 
> 漏写了一行导致的，现在在修了

9.0.1 已修复

**Comment by xzh12** [comment]
刚用了9.0.1试了，结果还是 “转码失败：该视频数据有误，请检查并修复视频数据后重新上传“

**Comment by MoyuScript** [comment]
> 刚用了9.0.1试了，结果还是 “转码失败：该视频数据有误，请检查并修复视频数据后重新上传“

我的没问题，这个你自己想办法了

**Comment by Gliese129** [comment]
> v9.0.0 已切换到 Web 端接口，无法上传多 p 视频了。另外就是接口参数有变化要注意一下，其他大体都没变

请问开发者知道access_key大概会保存多长时间吗

**Comment by Gliese129** [comment]
改成web端接口后我上传视频一直报403错误，查了三遍access_key，换了网络环境还是没用

**Comment by MoyuScript** [comment]
> 改成web端接口后我上传视频一直报403错误，查了三遍access_key，换了网络环境还是没用

Web 接口不使用 access_key 了，还是和其他接口一样使用 Credential

**Comment by Gliese129** [comment]
> > 改成web端接口后我上传视频一直报403错误，查了三遍access_key，换了网络环境还是没用
> 
> Web 接口不使用 access_key 了，还是和其他接口一样使用 Credential

换成Credential了，还是报403，代码是这样的
``` python
access_key = {
    'sessdata': my_sessdata,
    'bili_jct': my_bili_jct,
    'buvid3': my_buvid3
}

Class Uploader:

    def __init__(self, access_key: dict):
        self.credential = video_uploader.Credential(**access_key)

    async def upload():
        ......
        uploader = video_uploader.VideoUploader(pages=[page], meta=meta, credential=self.credential)
        await uploader.start()
```
报错信息：
![image](https://user-images.githubusercontent.com/32563762/140613954-f2d02b7c-a524-4266-a495-8ad4773e1e4d.png)

**Comment by MoyuScript** [comment]
> > > 改成web端接口后我上传视频一直报403错误，查了三遍access_key，换了网络环境还是没用
> > 
> > 
> > Web 接口不使用 access_key 了，还是和其他接口一样使用 Credential
> 
> 换成Credential了，还是报403，代码是这样的
> 
> ```python
> access_key = {
>     'sessdata': my_sessdata,
>     'bili_jct': my_bili_jct,
>     'buvid3': my_buvid3
> }
> 
> Class Uploader:
> 
>     def __init__(self, access_key: dict):
>         self.credential = video_uploader.Credential(**access_key)
> 
>     async def upload():
>         ......
>         uploader = video_uploader.VideoUploader(pages=[page], meta=meta, credential=self.credential)
>         await uploader.start()
> ```
> 
> 报错信息： ![image](https://user-images.githubusercontent.com/32563762/140613954-f2d02b7c-a524-4266-a495-8ad4773e1e4d.png)

是不是你填错了，我这边测试是正常的

**Comment by Gliese129** [comment]
> > > > 改成web端接口后我上传视频一直报403错误，查了三遍access_key，换了网络环境还是没用
> > > 
> > > 
> > > Web 接口不使用 access_key 了，还是和其他接口一样使用 Credential
> > 
> > 
> > 换成Credential了，还是报403，代码是这样的
> > ```python
> > access_key = {
> >     'sessdata': my_sessdata,
> >     'bili_jct': my_bili_jct,
> >     'buvid3': my_buvid3
> > }
> > 
> > Class Uploader:
> > 
> >     def __init__(self, access_key: dict):
> >         self.credential = video_uploader.Credential(**access_key)
> > 
> >     async def upload():
> >         ......
> >         uploader = video_uploader.VideoUploader(pages=[page], meta=meta, credential=self.credential)
> >         await uploader.start()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 报错信息： ![image](https://user-images.githubusercontent.com/32563762/140613954-f2d02b7c-a524-4266-a495-8ad4773e1e4d.png)
> 
> 是不是你填错了，我这边测试是正常的

查出来了，我把频道id填错了😂
