### ISSUE TITLE
【漏洞】原直播间信息获取接口失效

### ISSUE THREAD

**Issue by iyear** [MoyuScript/bilibili-api#244]
非Python开发者

https://github.com/MoyuScript/bilibili-api/blob/8f3fc2fcc4ddba369e8181dc1c5f9a3265a60982/bilibili_api/data/api/user.json#L37

原API: `https://api.live.bilibili.com/room/v1/Room/getRoomInfoOld` 已失效，返回接口已拦截

新的API: `https://api.bilibili.com/x/space/acc/info?mid=xxx`  无需鉴权，响应中的 `live_room` 与原接口字段一模一样

应该只是迁移了一下接口

**Comment by iyear** [comment]
原来接口的 `room_id` 为短号，现在返回的是真实直播间ID

**Comment by bakashigure** [comment]
我这里还能用(?
![image](https://user-images.githubusercontent.com/33803916/139520637-2b4718b5-b052-48e3-ad5b-680f00d134d0.png)

**Comment by iyear** [comment]
> 我这里还能用(? ![image](https://user-images.githubusercontent.com/33803916/139520637-2b4718b5-b052-48e3-ad5b-680f00d134d0.png)

看错API名字了😂，不好意思

是这个 https://github.com/MoyuScript/bilibili-api/blob/8f3fc2fcc4ddba369e8181dc1c5f9a3265a60982/bilibili_api/data/api/user.json#L37

**Comment by MoyuScript** [comment]
v9.0.0 已解决
