### ISSUE TITLE
【提问】下载视频时候卡住

### ISSUE THREAD

**Issue by Seanseattle** [MoyuScript/bilibili-api#249]
**Python 版本：** 3.7

**模块版本：** Video

**运行环境：** linux

**模块路径：** bilibili_api.video

**报错信息：**

```
File "get_videos.py", line 25, in <module>
    res = asyncio.get_event_loop().run_until_complete(main(bvid))
  File "xxx/python3.7/asyncio/base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "xxx/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "xxx/python3.7/asyncio/base_events.py", line 1750, in _run_once
    event_list = self._selector.select(timeout)
  File "xxx/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
```
**报错代码：**

```python
async with aiohttp.ClientSession(timeout=timeout, connector=connector) as sess:
            # 下载视频流
            async with sess.get(video_url, headers=HEADERS) as resp:
                length = resp.headers.get('content-length')
                with open('video_temp.m4s', 'wb') as f:
                    process = 0
                    while True:
                        chunk = await resp.content.read(1024)
                        if not chunk:
                            break

                        process += len(chunk)
                        print(f'下载视频流 {process} / {length}')
                        f.write(chunk)

```

---

您好，爬取视频时候会卡住，然后ctrl C就会报上面的错误。这是什么原因呀？

**Comment by Majjcom** [comment]
·KeyboardInterrupt·
这个是按下control-C之后Python底层的错误调用，不是爬取和下载的问题，
如果下载卡住的话可能是你的网络不太好，或者是源文件太大，

之前用aiohttp下载流媒体遇到过这样的问题
总之，解决方案：
1. 换网
2. 换系统
3. 换设备

我这边使用这套逻辑是没有问题的，可以参考一下我在写的项目

**Comment by Majjcom** [comment]
·KeyboardInterrupt·
这个是按下control-C之后Python底层的错误调用，不是爬取和下载的问题，
如果下载卡住的话可能是你的网络不太好，或者是源文件太大，

之前用aiohttp下载流媒体遇到过这样的问题
总之，解决方案：
1. 换网
2. 换系统
3. 换设备

我这边使用这套逻辑是没有问题的，可以参考一下我在写的项目

**Comment by Majjcom** [comment]
我这边用linux试了一下，好像不太行，可能是aiohttp的问题

windows是可以用的

**Comment by Majjcom** [comment]
我这边用linux试了一下，好像不太行，可能是aiohttp的问题

windows是可以用的

**Comment by bakashigure** [comment]
@Seanseattle 
  麻烦提供一下具体的运行环境？例如Linux发行版本，aiohttp的版本；
  或者试一下使用httpx?

**Comment by MoyuScript** [comment]
这个问题不属于漏洞，如果文件过大，你可以考虑分块下载，具体原理自行查询以下几个 http 头的定义：Range，Content-Length

**Comment by Seanseattle** [comment]
> @Seanseattle 麻烦提供一下具体的运行环境？例如Linux发行版本，aiohttp的版本； 或者试一下使用httpx?
感谢回复，这两个版本信息如下：
CentOS release 6.3 
aiohttp        3.7.4.post0.
这个具体原因是啥呀？我在window下试试看哈

**Comment by Seanseattle** [comment]
> 这个问题不属于漏洞，如果文件过大，你可以考虑分块下载，并自行编写超时机制。具体原理自行查询以下几个 http 头的定义：Range，Content-Length

是视频太大导致的bug吗？

**Comment by MoyuScript** [comment]
> > 这个问题不属于漏洞，如果文件过大，你可以考虑分块下载，并自行编写超时机制。具体原理自行查询以下几个 http 头的定义：Range，Content-Length
> 
> 是视频太大导致的bug吗？

下载大文件一般都要有分块下载、超时重传机制
