### ISSUE TITLE
【建议】是否应该在文档中标出api返回值中的具体参数？

### ISSUE THREAD

**Issue by bakashigure** [MoyuScript/bilibili-api#250]
rt，在代码闲聊群里不止一次遇到群友求助不知道该用哪个api，尤其是live模块下，有 `get_room_info` , `get_room_play_info`, `get_room_play_info_v2` , `get_gerenal_info` 等极具迷惑性的函数，是否可以考虑在文档中标出api返回值中的具体参数有哪些，分别的作用是什么？

**Comment by MoyuScript** [comment]
你让他们每个都调用一次就知道该用哪个了吧。说实话，我也不清楚这些接口都是些什么内容，要怪就怪b站设计接口的人吧🤣

**Comment by MoyuScript** [comment]
不对，我注释不是写了大概内容吗。要标明返回值的内容有哪些，这工作量怕不是要上十几倍，而且接口老是在变化，这项目就没法开发了🤣
