### ISSUE TITLE
弹幕爬取接口失效

### ISSUE THREAD

**Issue by Zonither** [MoyuScript/bilibili-api#258]
今天试了一下弹幕爬取，返回值如下：
 RequestsDependencyWarning: urllib3 (1.26.7) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "bilibili_hot.py", line 8, in <module>
    info = video.get_video_info(bvid=BVID)
AttributeError: module 'bilibili_api.video' has no attribute 'get_video_info'

**Comment by MoyuScript** [comment]
使用 issue 模板
