### ISSUE TITLE
error：pyinstaller 

### ISSUE THREAD

**Issue by 316902108** [MoyuScript/bilibili-api#261]
![image](https://user-images.githubusercontent.com/48303560/144182100-6c684847-6743-4ccb-997f-98d25448076a.png)
这里史用了绝对路径，打包后运行会找不到路径“path不存在  return回去的是None”！

**Comment by 316902108** [comment]
把 bilibili_api\data\api\live.json 中内容直接返回，问题可暂时得到解决

**Comment by MoyuScript** [comment]
使用模板发 issue
